### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by billylepandaroux** [EvotecIT/PSWinReporting#57]
Hi,

Your script is amazing but i've some memory issue. After script execution, RAM on DC is full at 98%

I used RAM MAP and it shows that security.evtx is still in active memory (as mapped file) 
![RoyalTS_7mMpbgO67L](https://user-images.githubusercontent.com/56294861/66382843-30997e80-e9bc-11e9-8f87-80a0a3563463.png)

your help would be appreciated.

best regards

**Comment by PrzemyslawKlys** [comment]
Which function are you using with what settings?

**Comment by billylepandaroux** [comment]
i use evotec's Monitoring Active Directory Changes on Users and Groups with PowerShell which use Get-EventsLibrary
https://evotec.xyz/monitoring-active-directory-changes-on-users-and-groups-with-powershell/
https://evotec.xyz/get-eventslibrary-ps1-monitoring-events-powershell/

**Comment by PrzemyslawKlys** [comment]
How big are your security logs?

**Comment by PrzemyslawKlys** [comment]
There are a few things I can recommend:
- smaller Security Log (I've worked with 1GB up to 60GB log files)
- choose a different machine to run the script on then your low memory DC
- you could limit the number of events you ask for 
- you could disable parallel processing (if you run it on the same machine it queries at the same time all DC's and depending on how many events you ask for it can query 1-3 times the security/application log per one DC

Finally, my favorite - enable log forwarding. Since you enable log forwarding of only crucial events for your reporting - all your DC's will send all their events you're interested in (and only those to ForwardedLog). This means you query just one log, one time. For me, it changed some queries from  15-60 or more minutes to 1minute and 15 seconds.

**Comment by billylepandaroux** [comment]
thanx again 👍 
Script is actually launched by another VM.
And since i limited the security logs size to 1gb, DCs have more free RAM.

but i still bother me that after running the script, DCs keep the file in memory as mapper :
![image](https://user-images.githubusercontent.com/56294861/66479370-a412bd00-ea9c-11e9-8564-f71f382418ac.png)

**Comment by PrzemyslawKlys** [comment]
Well not sure if we can do anything about it. It must be by design of Security Log to make logs quickly available. You should use forwarding then. Forward all relevant logs to your VM and it shouldn't query DC's at all. DC's will be sending new events as they come to your VM. Additional benefit is that you can get it to send information LIVE to your team as things happen.

**Comment by billylepandaroux** [comment]
i'll check that, thanx again 👍
